### ISSUE TITLE
omp_get_thread_num

### ISSUE THREAD

**Issue by lyelibi** [NeoNeuron/minfo#2]
Hello, I've been using your software to estimate mutual information for a while now, and suddenly I keep running into these issue. Would you know what to make of the following ? 

This happens when I try importing the library in my python scripts:

  File "/home/lionel/miniconda3/envs/perso/lib/python3.8/site-packages/minfo/__init__.py", line 3, in <module>
    from . import mi_float # dynamic lib must be imported after some other modules

ImportError: /home/lionel/miniconda3/envs/perso/lib/python3.8/site-packages/minfo/mi_float.cpython-38-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num

Any help is greatly appreciated.

**Comment by NeoNeuron** [comment]
Hi @lyelibi, sorry for the late reply. I've noticed this issue when I wrote and tested the code. It seems to be a common issue about the cython module faced by others. My temporal solution is that import other pure pythonic modules before cython module (just as the comments in the `minfo/__init__.py`).

https://github.com/NeoNeuron/minfo/blob/7258fbca2bee3b722ac6ce50821c72b1ad956328/minfo/__init__.py#L1-L3

In principle, if you install the original version of the package, this issue won't occur, unless you accidentally delete the first line in `minfo/__init__.py`. Could you please provide more details about your situation so that I can figure out what's going on. :smiley:
